config/routes.php
<?php
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    $routes->applyMiddleware('csrf');
    $routes->connect('/', ['controller' => 'Index', 'action' => 'index']);
    $routes->connect('/fornecedores', ['controller' => 'Clientes', 'action' => 'fornecedores']);
    $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
    $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/LotesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Lotes Model
 *
 * @property \App\Model\Table\FabricacaosTable|\Cake\ORM\Association\BelongsTo $Fabricacaos
 * @property \App\Model\Table\UnidadeMedidasTable|\Cake\ORM\Association\BelongsTo $UnidadeMedidas
 *
 * @method \App\Model\Entity\Lote get($primaryKey, $options = [])
 * @method \App\Model\Entity\Lote newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Lote[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Lote|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Lote|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Lote patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Lote[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Lote findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class LotesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('lotes');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Fabricacao', [
            'foreignKey' => 'fabricacao_id'
        ]);
        $this->belongsTo('UnidadeMedidas', [
            'foreignKey' => 'unidade_medida_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->nonNegativeInteger('id')
            ->allowEmptyString('id', 'create');

        $validator
            ->scalar('numero')
            ->maxLength('numero', 45)
            ->allowEmptyString('numero');

        $validator
            ->date('validade')
            ->allowEmptyDate('validade');

        $validator
            ->numeric('quantidade')
            ->greaterThanOrEqual('quantidade', 0)
            ->allowEmptyString('quantidade');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['fabricacao_id'], 'Fabricacao'));
        $rules->add($rules->existsIn(['unidade_medida_id'], 'UnidadeMedidas'));

        return $rules;
    }
}

src/Controller/FinanceiroController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

class FinanceiroController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->Compras = TableRegistry::get('Compras');
        $this->Pedidos = TableRegistry::get('Pedidos');
        $this->PedidoProdutos = TableRegistry::get('PedidoProdutos');
        //$this->Vendas = TableRegistry::get('Vendas');
    }

    public function index()
    {
    }

    public function compras()
    {
        $this->paginate = [
            'contain' => ['ItensNotas'=>'MateriaPrimas','Clientes']
        ];
        $compras = $this->paginate($this->Compras);
        $this->set(compact('compras'));
    }

    public function novaCompra()
    {
        $compra = $this->Compras->newEntity();
        if($this->request->is('post'))
        {
            $compra = $this->Compras->patchEntity($compra, $this->request->getData());
            $compra->data .= $this->request->getData('data').' 00:00:00';
            $compra = $this->Compras->save($compra);
            if($compra)
            {
                $itens = $this->request->getData('item');
                $qtd = $this->request->getData('qtd');
                $vlr = $this->request->getData('vlr');
                $total = 0;
                foreach($itens as $k => $v)
                {
                    $this->ItensNota = TableRegistry::get('ItensNotas');
                    $newItemNota = $this->ItensNota->newEntity();
                    $newItemNota->nota_id = $compra->id;
                    $newItemNota->tipo_nota = 'C';
                    $newItemNota->item = $v;
                    $newItemNota->quantidade = $qtd[$k];
                    $newItemNota->valor_unitario = $vlr[$k];
                    $total = $total + $newItemNota->valor_unitario;
                    $this->ItensNota->save($newItemNota);
                }
                $compra->valor_total = $total;  
                $this->Compras->save($compra);
                return $this->redirect(['action'=>'compras']);
            }else{
                die(var_dump($compra));
            }
        }
        $fornecedores = $this->Compras->Clientes->find('list')->where(['tipo IN '=>['A','F']])->order(['nome']);
        $forma_pagamentos = $this->Compras->FormaPagamentos->find('list');
        $tipos = TableRegistry::get('TipoMateriaPrimas')->find('all',['fields'=>['id','nome']]);
        $this->set(compact('compra','fornecedores','forma_pagamentos','tipos'));
    }

    public function pedidos()
    {
        $this->paginate = [
            'contain' => ['Clientes','PedidoProdutos'=>['Produtos','UnidadeMedidas']]
        ];
        $pedidos = $this->paginate($this->Pedidos);
        $this->set(compact('pedidos'));
    }

    public function novoPedido()
    {
        $pedido = $this->Pedidos->newEntity();
        if($this->request->is('post'))
        {
            $dados = $this->request->getData();
            $pedido = $this->Pedidos->newEntity();
            $pedido->cliente_id = $dados['cliente_id'];
            $pedido->data_pedido = parent::acertaData($dados['data_pedido']);
            $pedido->previsao_entrega = parent::acertaData($dados['previsao_entrega']);
            $pedido->situacao = 0;
            $pedido->pago = 0;
            $pedido = $this->Pedidos->save($pedido);
            if($pedido)
            {
                foreach($dados['item'] as $k => $v)
                {
                    $item_pedido = $this->PedidoProdutos->newEntity();
                    $item_pedido->pedido_id = $pedido->id;
                    $item_pedido->produto_id = $v;
                    $item_pedido->quantidade = $dados['qtd'][$v];
                    $item_pedido->unidade_medida_id = $dados['und'][$v];
                    $item_pedido->valor_combinado = $dados['vlr'][$v];
                    if($item_pedido->valor_combinado==0)
                    {
                        $_unidade = TableRegistry::get('UnidadeMedidas',['contains'=>'ParentUnidadeMedidas'])->get($item_pedido->unidade_medida_id);
                        $_valor = TableRegistry::get('Produtos')->get($item_pedido->produto_id);
                        if($_unidade->parent_id!=null){
                            $_mult = $_unidade->fator_multiplicativo;
                        }else{
                            $_mult = 1;
                        }
                        if($_valor->atacado_minimo<=($item_pedido->quantidade*$_mult))
                        {
                            $valor = $_valor->valor_atacado;
                        }else{
                            $valor = $_valor->valor_varejo;
                        }
                        $item_pedido->valor_combinado = $valor;
                    }
                    $item_pedido->entregue = 0;
                    $this->PedidoProdutos->save($item_pedido);
                }
                $this->Flash->success('Pedido salvo com sucesso!');
                return $this->redirect(['action'=>'pedidos']);
            }
        }
        $clientes = $this->Pedidos->clientes->find('list')->where(['tipo IN'=>['C','A']])->order(['nome'=>'desc']);
        $produtos = $this->Pedidos->PedidoProdutos->Produtos->find('list')->order(['nome'=>'desc']);
        $unidades = TableRegistry::get('UnidadeMedidas')->find('list')->order(['nome'=>'desc']);
        $this->set(compact('pedido','clientes','produtos','unidades'));
    }
}

src/Template/Financeiro/compras.ctp
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Compras realizadas<?=$this->Html->link('<i class="fe fe-plus"></i> Nova compra', ['action'=>'novaCompra'],['class'=>'btn btn-pill btn-success btn-sm float-right','escape'=>false])?></h3>
        </div>
        <div class="card-body">
            <table class="table card-table table-vcenter">
                <thead>
                    <tr>
                        <th scope="col">#ID</th>
                        <th scope="col">Fornecedor</th>
                        <th scope="col">Data</th>
                        <th scope="col">Valor</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach($compras as $c)
                    {
                    ?>
                    <tr>
                        <td><i class="detalhar fe fe-arrow-down-circle" data-attr="det_<?=$c->id;?>"></i> <?=$c->id;?></td>
                        <td><?=$c->cliente->nome;?></td>
                        <td><?=$c->data;?></td>
                        <td><?=$c->valor_total;?></td>
                    </tr>
                    <tr id="det_<?=$c->id;?>" style="display:none">
                        <td colspan="4">
                            <div class="jumbotron p-2">
                                <table class="table card-table table-vcenter">
                                    <thead>
                                        <tr>
                                            <th scope="col">#ID</th>
                                            <th scope="col">Item</th>
                                            <th scope="col">Quantidade</th>
                                            <th scope="col">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach($c->itens_notas as $i)
                                        {
                                        ?>
                                        <tr>
                                            <td><?=$i->id;?></td>
                                            <td><?=$i->materia_prima->nome;?></td>
                                            <td><?=$i->quantidade;?></td>
                                            <td>R$ <?=number_format($i->valor_unitario,2,',','.')?></td>
                                        </tr>
                                        <?php
                                        }
                                        ?>
                                    </tbody>
                            </div>
                        </td>
                    </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex align-items-center mb-4">
        <ul class="pagination">
            <?= $this->Paginator->first('<<') ?>
            <?= $this->Paginator->prev('<') ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next('>') ?>
            <?= $this->Paginator->last('>>') ?>
        </ul>
        <div class="page-total-text"><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></div>
    </div>
</div>
<script>
    $(document).on('click','.detalhar',function(){
        $('#'+$(this).attr('data-attr')).toggle(200);
    });
</script>

src/Template/Financeiro/nova_compra.ctp
<div class="col-12">
    <div class="card">
        <?= $this->Form->create($compra) ?>
        <div class="card-header">
            <h3 class="card-title">Nova compra</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <?=$this->Form->control('numero_nota',['class'=>'form-control']);?>
                </div>
                <div class="col-md-6">
                    <?=$this->Form->control('cliente_id',['label'=>'Fornecedor','empty'=>' - Selecione o fornecedor - ','class'=>'form-control', 'options'=>$fornecedores, 'required']);?>
                </div>
                <div class="col-md-3">
                    <?=$this->Form->control('data',['class'=>'form-control','type'=>'text']);?>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-3 p-2" style="background-color:#eeeeee">
                        <div class="row">
                            <div class="col-md-2">
                                <label for="tipo">Tipo</label>
                                <select name="tipo" id="tipo" class="form-control">
                                    <option value="0"> - Selecione - </option>
                                    <?php
                                    foreach($tipos as $tp)
                                    {
                                    ?>
                                    <option value="<?=$tp->id;?>"><?=$tp->nome;?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="materia">Materia prima</label>
                                <select name="materia" id="materia" class="form-control">
                                    <option value=""> - Selecione o tipo - </option>
                                </select>
                            </div>
                            <div class="col-md-1">
                                <label for="quantidade">Quantidade</label>
                                <input type="text" name="quantidade" id="quantidade" class="form-control">
                            </div>
                            <div class="col-md-2">
                                <label for="valor">Valor</label>
                                    <input type="text" name="valor" id="valor" class="form-control">
                                </div>
                            <div class="col-md-1 mt-6">
                                <button class="btn btn-outline btn-sm" type="button" id="addmp" nome="addmp"><i class="fe fe-plus"></i></button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <table class="table card-table table-vcenter" id="itens-nota">
                                    <thead>
                                        <th>Produto</th>
                                        <th>Quantidade</th>
                                        <th>Valor</th>
                                        <th class="actions"></th>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
            <div class="col-md-3 offset-md-5">
                    <?=$this->Form->control('forma_pagamento_id',['class'=>'form-control','options'=>$forma_pagamentos, 'empty'=>' - Selecione a forma - ', 'required']);?>
                </div>
                <div class="col-md-3">
                    <?=$this->Form->control('frete',['class'=>'form-control']);?>
                </div>
                <div class="col-md-1" style="margin-top:35px">
                    <label class="custom-switch">
                        <input type="checkbox" name="pago" id="pago" class="custom-switch-input" value="1">
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">pago</span>
                    </label>              
                </div>
            </div>
        </div>
        <div class="card-footer">
            <?=$this->Form->button(' Gravar ', ['class'=>'btn btn-success']) ?>
        </div>
        <?= $this->Form->end() ?>
    </div>
</div>
<script>
    $(document).on('change','#tipo',function(){
        obj = $(this);
        $.ajax({
            type: "POST",
            url: "<?=$this->Url->build(['controller'=>'MateriaPrimas', 'action'=>'busca'])?>",
            async: true,
            data: {tipo_id: obj.val()},
            dataType: "json",
            beforeSend: function(xhr){
                xhr.setRequestHeader('X-CSRF-Token', <?=json_encode($this->request->getParam('_csrfToken'));?>);
            },
            success: function(json){
                var html = "<option value=''> - Selecione uma matéria-prima - </option>";
                $.each(json.retorno, function(i,item){
                    html += "<option value='"+item.id+"'>"+item.nome+"</option>";
                });
                $('#materia').html(html);
            }
        });         
    });

    $(document).on('click', '#addmp', function(){
        if(($('#materia').val()=='')||($('#quantidade').val()=='')||($('#valor').val()=='')){
            alert('Prencha todos os campos antes!');
        }else{
            var _linha = '<tr><td>'+$('#materia option:selected').text()+'<input type="hidden" name="item[]" value="'+$('#materia option:selected').val()+'"><input type="hidden" name="qtd[]" value="'+$('#quantidade').val()+'"><input type="hidden" name="vlr[]" value="'+$('#valor').val()+'"></td><td>'+$('#quantidade').val()+'</td><td>R$ '+$('#valor').val()+'</td><td class="actions"><i class="fe fe-trash" style="color:red" id="n"></i></td></tr>';
            $('#itens-nota').append(_linha);
            $('#tipo').val(0).trigger('change');
            $('#materia').html("<option value=''> - Selecione um tipo - </option>");
            $('#quantidade').val('');
            $('#valor').val('');
        }
    });
</script>

src/Template/Financeiro/novo_pedido.ctp
<div class="col-12">
    <div class="card">
        <?= $this->Form->create($pedido) ?>
        <div class="card-header">
            <h3 class="card-title">Novo pedido</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <?=$this->Form->control('cliente_id',['label'=>'Cliente','empty'=>' - Selecione o cliente - ','class'=>'form-control', 'options'=>$clientes, 'required']);?>
                </div>
                <div class="col-md-3">
                    <?=$this->Form->control('data_pedido',['label'=>'Data do pedido','class'=>'form-control','type'=>'text']);?>
                </div>
                <div class="col-md-3">
                    <?=$this->Form->control('previsao_entrega',['label'=>'Previsão de entrega','class'=>'form-control','type'=>'text']);?>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-3 p-2" style="background-color:#eeeeee">
                        <div class="row">
                            <div class="col-md-5">
                                <?=$this->Form->control('produto_id',['label'=>'Produto','class'=>'form-control']);?>
                            </div>
                            <div class="col-md-2">
                                <label for="quantidade">Quantidade</label>
                                <input type="text" name="quantidade" id="quantidade" class="form-control">
                            </div>
                            <div class="col-md-2">
                                <?=$this->Form->control('unidade', ['label'=>'Unidade', 'options'=>$unidades, 'empty'=>' - selecione - ','class'=>'form-control']);?>
                            </div>
                            <div class="col-md-2">
                                <label for="valor">Valor <b>unitário</b> combinado</label>
                                <input type="text" name="valor" id="valor" class="form-control">
                            </div>
                            <div class="col-md-1 mt-6">
                                <button class="btn btn-outline btn-sm" type="button" id="addmp" nome="addmp"><i class="fe fe-plus"></i></button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <table class="table card-table table-vcenter" id="itens-nota">
                                    <thead>
                                        <th>Produto</th>
                                        <th>Quantidade</th>
                                        <th>Unidade</th>
                                        <th>Valor</th>
                                        <th class="actions"></th>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <?=$this->Form->button(' Gravar ', ['class'=>'btn btn-success']) ?>
        </div>
        <?= $this->Form->end() ?>
    </div>
</div>
<script>
    $(document).on('change','#tipo',function(){
        obj = $(this);
        $.ajax({
            type: "POST",
            url: "<?=$this->Url->build(['controller'=>'MateriaPrimas', 'action'=>'busca'])?>",
            async: true,
            data: {tipo_id: obj.val()},
            dataType: "json",
            beforeSend: function(xhr){
                xhr.setRequestHeader('X-CSRF-Token', <?=json_encode($this->request->getParam('_csrfToken'));?>);
            },
            success: function(json){
                var html = "<option value=''> - Selecione uma matéria-prima - </option>";
                $.each(json.retorno, function(i,item){
                    html += "<option value='"+item.id+"'>"+item.nome+"</option>";
                });
                $('#materia').html(html);
            }
        });         
    });

    $(document).on('click', '#addmp', function(){
        if(($('#materia').val()=='')||($('#quantidade').val()=='')||($('#valor').val()=='')){
            alert('Prencha todos os campos antes!');
        }else{
            var _linha = '<tr><td>'+$('#produto-id option:selected').text()+'<input type="hidden" name="item[]" value="'+$('#produto-id option:selected').val()+'"><input type="hidden" name="qtd['+$('#produto-id option:selected').val()+']" value="'+$('#quantidade').val()+'"><input type="hidden" name="und['+$('#produto-id option:selected').val()+']" value="'+$('#unidade option:selected').val()+'"><input type="hidden" name="vlr['+$('#produto-id option:selected').val()+']" value="'+$('#valor').val()+'"></td><td>'+$('#quantidade').val()+'</td><td>'+$('#unidade option:selected').text()+'</td><td>R$ '+$('#valor').val()+'</td><td class="actions"><i class="fe fe-trash" style="color:red" id="n"></i></td></tr>';
            $('#itens-nota').append(_linha);
            $('#produto-id').val(null);
            $('#unidade').val(null);
            $('#quantidade').val('');
            $('#valor').val('');
        }
    });
</script>

src/Template/Financeiro/pedidos.ctp
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Pedidos recebidos <?=$this->Html->link('<i class="fe fe-plus"></i> Novo pedido', ['action'=>'novoPedido'],['class'=>'btn btn-pill btn-success btn-sm float-right','escape'=>false])?></h3>
        </div>
        <div class="card-body">
            <table class="table card-table table-vcenter">
                <thead>
                    <tr>
                        <th scope="col">#ID</th>
                        <th scope="col">Cliente</th>
                        <th scope="col">Data</th>
                        <th scope="col">Previsão</th>
                        <th scope="col">Entrega</th>
                        <th scope="col" class="actions"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach($pedidos as $c)
                    {
                    ?>
                    <tr>
                        <td><i class="detalhar fe fe-arrow-down-circle" data-attr="det_<?=$c->id;?>"></i> <?=$c->id;?></td>
                        <td><?=$c->cliente->nome;?></td>
                        <td><?=date('d/m/Y', strtotime($c->data_pedido));?></td>
                        <td><?=$c->previsao_entrega!=''?date('d/m/Y', strtotime($c->previsao_entrega)):'';?></td>
                        <td><?=$c->data_entrega!=''?date('d/m/Y', strtotime($c->data_entrega)):'';?></td>
                        <td class="actions">Finalizar Editar Cancelar</td>
                    </tr>
                    <tr id="det_<?=$c->id;?>" style="display:none">
                        <td colspan="6">
                            <div class="jumbotron p-2">
                                <table class="table card-table table-vcenter">
                                    <thead>
                                        <tr>
                                            <th scope="col">#ID</th>
                                            <th scope="col">Item</th>
                                            <th scope="col">Quantidade</th>
                                            <th scope="col">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach($c->pedido_produtos as $i)
                                        {
                                        ?>
                                        <tr>
                                            <td><?=$i->id;?></td>
                                            <td><?=$i->produto->nome;?></td>
                                            <td><?=$i->quantidade.' '.$i->unidade_medida->sigla;?></td>
                                            <td>R$ <?=number_format($i->valor_combinado*$i->quantidade,2,',','.')?></td>
                                        </tr>
                                        <?php
                                        }
                                        ?>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex align-items-center mb-4">
        <ul class="pagination">
            <?= $this->Paginator->first('<<') ?>
            <?= $this->Paginator->prev('<') ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next('>') ?>
            <?= $this->Paginator->last('>>') ?>
        </ul>
        <div class="page-total-text"><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></div>
    </div>
</div>
<script>
    $(document).on('click','.detalhar',function(){
        $('#'+$(this).attr('data-attr')).toggle(200);
    });
</script>